void main() {
  var list = new List();
  var total = 0;
  var details = {
    'Item Id': 1,
    'Price': 25000,
    'Quantity': 1,
    'Discount': 10,
  };

  list.add(details);
  // ignore: unused_local_variable
  var output = {
    'Item Id': 2,
    'Price': 5000,
    'Quantity': 1,
    'Discount': 10,
  };
  list.add(output);
  // ignore: unused_local_variable
  var item = {
    'Item Id': 3,
    'Price': 1500,
    'Quantity': 1,
    'Discount': 10,
  };
  list.add(item);
  var id = {'Item Id': 4, 'Price': 3000, 'Quantity': 10, 'Discount': 20};
  list.add(id);

  var information = {
    'Item Id': 5,
    'Price': 50000,
    'Quantity': 10,
    'Discount': 20
  };
  list.add(information);
  var head = ['Item Id', 'Price', 'Quantity', 'Discount'];

  list.forEach((map) {
    head.forEach((model) {
      print(model + ':' + map[model].toString());
    });
    int subtotal = (map['Price'] * map['Quantity']) -
        (map['Discount'] * (map['Price'] * map['Quantity']) ~/ 100);
    total += subtotal;
    print('Sub total:$subtotal');

    print('');
  });
  print('Total Amount Payable:$total');
}

class Calculate_Total {
  // ignore: missing_return
  int ret_tot() {}
}

class Calculate_TotalAmountPayable {
  // ignore: missing_return
  int ret_dis() {}
}

class Calculator implements Calculate_Total, Calculate_TotalAmountPayable {
  int ret_tot() {
    return 1000;
  }

  int ret_dis() {
    return 452350;
  }
}

